apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.demo.example.com
spec:
  group: demo.example.com
  names:
    plural: widgets
    singular: widget
    kind: Widget
    shortNames:
      - wgt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              additionalProperties: false # UnknownStrict for spec
              properties:
                name:
                  type: string
                replicas:
                  type: integer
                  default: 1
                note:
                  type: string
                  nullable: true
                labels:
                  type: object
                  additionalProperties:
                    type: string
                items:
                  type: array
                  items:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: string
                      port:
                        type: integer
              required:
                - name
          required:
            - spec


