apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
              namespace:
                type: string
          spec:
            type: object
            additionalProperties: false
            properties:
              size:
                type: string
                enum: ["small", "medium", "large"]
                description: "Size of the widget"
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                description: "Number of replicas"
              config:
                type: object
                additionalProperties: false
                properties:
                  timeout:
                    type: string
                    pattern: '^[0-9]+[smh]$'
                    description: "Timeout duration (e.g., 30s, 5m, 1h)"
                  retries:
                    type: integer
                    minimum: 0
                    maximum: 5
                    description: "Number of retries"
                description: "Configuration options"
            required: ["size", "replicas"]
            description: "Widget specification"
        required: ["spec"]
  scope: Namespaced
  names:
    plural: widgets
    singular: widget
    kind: Widget
    shortNames: ["wdg"]
